GAME_FIELD_ROWS = 25
GAME_FIELD_COLS = 50
LANDMINE_HEIGHT = 1
LANDMINE_WIDTH = 3
SOLDIER_HEIGHT = 4
SOLDIER_WIDTH = 2
FLAG_HEIGHT = 3
FLAG_WIDTH = 4

CELL_SIDE_LENGTH = 20  # cell is squared
TITLE_TEXT = 'Welcome to The Flag game. Have Fun!'
WHITE = (255, 255, 255)
GRASS_COLOR = (1, 70, 25)
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500

